# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
- group: semgrep-variables

resources:
  repositories:
  - repository: repo1/repo1
    type: git
    name: repo1/repo1
    trigger:
      branches:
        include:
        - '*'
  - repository: repo2/repo2
    type: git
    name: repo2/repo2
    trigger:
      branches:
        include:
        - main


pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: repo1/repo1
  persistCredentials: true
  clean: true
  fetchDepth: 0
  path: ./repo
- checkout: self
  clean: true
  fetchDepth: 0
  path: ./self
- script: |
    cd /home/vsts/work/1
    pip install azure-devops
    export SYSTEM_ACCESSTOKEN=$(System.AccessToken)
    export BASLINE_REF=`cd repo && git merge-base HEAD`
    echo "------------------------------------------------------------------------------"
    export REPO_DISPLAY_NAME=$(echo "$(Build.Repository.Uri)" | sed 's|.*dev.azure.com/||' | sed 's|_git/||')
    python ./self/check_prs.py 
    env
  env:
    SEMGREP_APP_TOKEN: $(SEMGREP_APP_TOKEN)


# - checkout: repo2
# - script: |
#     ls -alh
#     cat repo2/readme.md
#     cat readme.md
#   displayName: 'Run a cat'


#    docker run \
#       -v "./:/src" \
#       -e SEMGREP_APP_TOKEN=$(SEMGREP_APP_TOKEN) \
#       -e SEMGREP_REPO_DISPLAY_NAME="$REPO_DISPLAY_NAME" \
#       -i semgrep/semgrep semgrep ci