trigger: none
stages:
  - stage: Trigger
    pool:
      vmImage: ubuntu-latest
    variables:
      - group: semgrep-pipeline-vg
      - name: pullRequestId
        value: $[variables['system.pullRequest.pullRequestId']]
      - name: sourceBranch
        value: $[variables['system.pullRequest.sourceBranch']]
      - name: targetBranch
        value: $[variables['system.pullRequest.targetBranch']]
      - name: sourceCommitId
        value: $[variables['system.pullRequest.sourceCommitId']]
      - name: sourceRepositoryUri
        value: $[variables['system.pullRequest.sourceRepositoryUri']]
      - name: workingDirectory
        value: $(Build.SourcesDirectory)/scan-triggering/build-validation-trigger
    jobs:
      - job:
        displayName: Trigger Semgrep Scan Pipeline
        steps:
          - task: UseNode@1
            inputs:
              version: "20.x"
            displayName: "Install Node.js"

          - script: |
              npm install
            displayName: "npm install"
            workingDirectory: $(workingDirectory)

          - script: |
              npm run build && npm start
            displayName: Invoke Semgrep Pipeline
            workingDirectory: $(workingDirectory)
            env:
              ORG_URL: $(ORG_URL)
              AZURE_TOKEN: $(AZURE_TOKEN)
              PROJECT_NAME: $(PROJECT_NAME)
              PIPELINE_ID: $(PIPELINE_ID)
              SOURCE_REPOSITORY_URI: $(sourceRepositoryUri)
              PULL_REQUEST_ID: $(pullRequestId)
              SOURCE_COMMIT_ID: $(sourceCommitId)
              SOURCE_BRANCH: $(sourceBranch)
              TARGET_BRANCH: $(targetBranch)
